site_name: AutoML mljar-supervised 

theme:
    name: material
    #custom_dir: overrides
    favicon: images/favicon.png
    icon:
        repo: fontawesome/brands/github-square
        logo: fontawesome/solid/book-open
    palette:
        primary: blue


repo_url: https://github.com/mljar/mljar-supervised
repo_name: mljar-supervised

markdown_extensions:
    - pymdownx.highlight:
        use_pygments: true
    - toc:
        permalink: true
    - codehilite
    - pymdownx.tabbed
    - pymdownx.superfences
    - admonition
    - pymdownx.details

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/mljar/mljar-supervised
        - icon: fontawesome/brands/slack
          link: https://mljar-supervised.slack.com/join/shared_invite/zt-gkhfsvhw-H6LMKxxV5adeTmn9V7nbZw#/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/MLJARofficial
        - icon: fontawesome/regular/lightbulb
          link: https://mljar.com
    font:
        - text: 'Ubuntu'
        - code: 'Ubuntu Mono'

copyright: Copyright Â© MLJAR, Inc.

